name: lakiite
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  go_router: ^7.0.1
  hooks_riverpod: ^2.4.10
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  state_notifier: ^1.0.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.7.7
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  google_mobile_ads: ^4.0.0
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  riverpod_generator: ^2.3.11
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutterfire_cli: ^1.0.1-dev.4
  analyzer: ^5.13.0

flutter:
  uses-material-design: true

dependency_overrides:
  watcher: ^1.1.0
