// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Production [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: ProdFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'ProdFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 本番環境用の設定
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs9MZx-uHkBFipz-4XVL98TfL7e8Vw_3c',
    appId: '1:472076922540:web:d31d66cf2f86e9aec87909',
    messagingSenderId: '472076922540',
    projectId: 'lakiite-flutter-app-prod',
    authDomain: 'lakiite-flutter-app-prod.firebaseapp.com',
    storageBucket: 'lakiite-flutter-app-prod.firebasestorage.app',
    measurementId: 'G-8EE3FQJFML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL-T51PzotyEZbM1C1TsRbxyu10oboVpo',
    appId: '1:817472600275:android:5fcab2f2e32f30de363c26',
    messagingSenderId: '817472600275',
    projectId: 'lakiite-flutter-app-prod',
    storageBucket: 'lakiite-flutter-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkFJEMtoIKW2VQVFIpNe0MboQmRlP5ZIQ',
    appId: '1:817472600275:ios:db5c7dc7387de369363c26',
    messagingSenderId: '817472600275',
    projectId: 'lakiite-flutter-app-prod',
    storageBucket: 'lakiite-flutter-app-prod.firebasestorage.app',
    iosBundleId: 'com.inoworl.lakiite',
  );
}
