// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Development [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DevFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DevFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs9MZx-uHkBFipz-4XVL98TfL7e8Vw_3c',
    appId: '1:472076922540:web:d31d66cf2f86e9aec87909',
    messagingSenderId: '472076922540',
    projectId: 'tarakite-flutter-app-dev',
    authDomain: 'tarakite-flutter-app-dev.firebaseapp.com',
    storageBucket: 'tarakite-flutter-app-dev.firebasestorage.app',
    measurementId: 'G-8EE3FQJFML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwFaBJx7sjU809f4FEECTxj9x2Q3qTeks',
    appId: '1:472076922540:android:6a778759d8c9f1cac87909',
    messagingSenderId: '472076922540',
    projectId: 'tarakite-flutter-app-dev',
    storageBucket: 'tarakite-flutter-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHxYnS4-B_M98ABIwrY9QnzRNd67WiRaY',
    appId: '1:472076922540:ios:763d5c1e1aad5d2ec87909',
    messagingSenderId: '472076922540',
    projectId: 'tarakite-flutter-app-dev',
    storageBucket: 'tarakite-flutter-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.tarakite',
  );
}
